# Generated by Django 4.0.1 on 2022-07-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_id', models.CharField(default='DEFAULT', max_length=32)),
                ('base_text', models.CharField(default='DEFAULT', max_length=512)),
                ('latitude', models.FloatField(default=999)),
                ('longitude', models.FloatField(default=999)),
                ('runway', models.IntegerField(default=999)),
                ('year', models.IntegerField(default=999)),
                ('month', models.IntegerField(default=999)),
                ('day', models.IntegerField(default=999)),
                ('hour', models.IntegerField(default=999)),
                ('weather', models.CharField(default='weather', max_length=512)),
                ('air_temp', models.FloatField(default=999)),
                ('dew_point', models.FloatField(default=999)),
                ('wind_direction', models.IntegerField(default=999)),
                ('cross_wind', models.FloatField(default=999)),
                ('wind_gust_speed', models.FloatField(default=999)),
                ('peak_wind_speed', models.FloatField(default=999)),
                ('precipitation', models.FloatField(default=999)),
                ('visibility', models.IntegerField(default=999)),
                ('cloud_cover', models.CharField(default='DEFAULT', max_length=64)),
                ('cloud_ceiling', models.IntegerField(default=999)),
                ('icing_percentage_low', models.FloatField(default=999)),
                ('icing_percentage_med', models.FloatField(default=999)),
                ('icing_percentage_high', models.FloatField(default=999)),
            ],
        ),
    ]
