# Generated by Django 4.0.6 on 2022-07-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='visibility',
            field=models.IntegerField(default=999, max_length=64),
        ),
    ]
