name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main","Dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: isbang/compose-action@v1.1.0
      with:
        compose-file: "./docker-compose.yml"
        up-flags: "--abort-on-container-exit, --exit-code-from test-service, --build"